/**
 * Whole foods nutrition database — sourced from USDA FoodData Central.
 * 200 whole foods with per-100g macros and gram-accurate serving sizes.
 * Generated from whole_foods_nutrition.xlsx.
 */

export type FoodCategory =
  | 'protein'
  | 'dairy'
  | 'vegetables'
  | 'fruits'
  | 'grains'
  | 'nuts'
  | 'fats'
  | 'other';

export interface UsdaServing {
  label: string;
  grams: number;
  isDefault?: boolean;
}

export interface UsdaFood {
  name: string;
  category: FoodCategory;
  per100g: {
    protein: number;
    fat: number;
    carbs: number;
    calories: number;
    fiber?: number;
    sodium?: number;
    sugar?: number;
  };
  servings: UsdaServing[];
}

export const USDA_FOODS: UsdaFood[] = [
  {
    name: "Broccoli, raw",
    category: "vegetables",
    per100g: { protein: 2.7, fat: 0.3, carbs: 6.6, calories: 34.1, fiber: 2.6, sugar: 1.6, sodium: 33 },
    servings: [
      { label: "46g (half serving)", grams: 46 },
      { label: "1 cup chopped (91g)", grams: 91, isDefault: true },
      { label: "137g (1½ servings)", grams: 137 },
      { label: "182g (double)", grams: 182 },
    ],
  },
  {
    name: "Spinach, raw",
    category: "vegetables",
    per100g: { protein: 3, fat: 0.3, carbs: 3.7, calories: 23.3, fiber: 2.3, sugar: 0.3, sodium: 80 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "1 cup (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Kale, raw",
    category: "vegetables",
    per100g: { protein: 2.9, fat: 0.5, carbs: 6.7, calories: 33.3, fiber: 4.3, sugar: 1, sodium: 52.4 },
    servings: [
      { label: "11g (half serving)", grams: 11 },
      { label: "1 cup chopped (21g)", grams: 21, isDefault: true },
      { label: "32g (1½ servings)", grams: 32 },
      { label: "42g (double)", grams: 42 },
    ],
  },
  {
    name: "Carrot, raw",
    category: "vegetables",
    per100g: { protein: 1, fat: 0.2, carbs: 9.5, calories: 41, fiber: 2.8, sugar: 4.8, sodium: 68.9 },
    servings: [
      { label: "31g (half serving)", grams: 31 },
      { label: "1 medium (61g)", grams: 61, isDefault: true },
      { label: "92g (1½ servings)", grams: 92 },
      { label: "122g (double)", grams: 122 },
    ],
  },
  {
    name: "Bell pepper, red",
    category: "vegetables",
    per100g: { protein: 1, fat: 0.3, carbs: 6.1, calories: 31.1, fiber: 2.1, sugar: 4.2, sodium: 5 },
    servings: [
      { label: "60g (half serving)", grams: 60 },
      { label: "1 medium (119g)", grams: 119, isDefault: true },
      { label: "179g (1½ servings)", grams: 179 },
      { label: "238g (double)", grams: 238 },
    ],
  },
  {
    name: "Bell pepper, green",
    category: "vegetables",
    per100g: { protein: 0.8, fat: 0.2, carbs: 4.6, calories: 20.2, fiber: 1.8, sugar: 2.4, sodium: 3.4 },
    servings: [
      { label: "60g (half serving)", grams: 60 },
      { label: "1 medium (119g)", grams: 119, isDefault: true },
      { label: "179g (1½ servings)", grams: 179 },
      { label: "238g (double)", grams: 238 },
    ],
  },
  {
    name: "Tomato, raw",
    category: "vegetables",
    per100g: { protein: 0.9, fat: 0.2, carbs: 3.9, calories: 17.9, fiber: 1.2, sugar: 2.6, sodium: 4.9 },
    servings: [
      { label: "62g (half serving)", grams: 62 },
      { label: "1 medium (123g)", grams: 123, isDefault: true },
      { label: "185g (1½ servings)", grams: 185 },
      { label: "246g (double)", grams: 246 },
    ],
  },
  {
    name: "Cucumber",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.1, carbs: 3.7, calories: 15.4, fiber: 0.5, sugar: 1.6, sodium: 1.9 },
    servings: [
      { label: "52g (half serving)", grams: 52 },
      { label: "1 cup sliced (104g)", grams: 104, isDefault: true },
      { label: "156g (1½ servings)", grams: 156 },
      { label: "208g (double)", grams: 208 },
    ],
  },
  {
    name: "Celery",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.2, carbs: 3, calories: 15.8, fiber: 1.6, sugar: 1.8, sodium: 80.2 },
    servings: [
      { label: "51g (half serving)", grams: 51 },
      { label: "1 cup chopped (101g)", grams: 101, isDefault: true },
      { label: "152g (1½ servings)", grams: 152 },
      { label: "202g (double)", grams: 202 },
    ],
  },
  {
    name: "Lettuce, romaine",
    category: "vegetables",
    per100g: { protein: 1.3, fat: 0.2, carbs: 3.2, calories: 17, fiber: 2.1, sugar: 1.3, sodium: 8.5 },
    servings: [
      { label: "24g (half serving)", grams: 24 },
      { label: "1 cup shredded (47g)", grams: 47, isDefault: true },
      { label: "71g (1½ servings)", grams: 71 },
      { label: "94g (double)", grams: 94 },
    ],
  },
  {
    name: "Cauliflower, raw",
    category: "vegetables",
    per100g: { protein: 2, fat: 0.3, carbs: 5, calories: 25.2, fiber: 2, sugar: 1.9, sodium: 29.9 },
    servings: [
      { label: "54g (half serving)", grams: 54 },
      { label: "1 cup chopped (107g)", grams: 107, isDefault: true },
      { label: "161g (1½ servings)", grams: 161 },
      { label: "214g (double)", grams: 214 },
    ],
  },
  {
    name: "Brussels sprouts, raw",
    category: "vegetables",
    per100g: { protein: 3.4, fat: 0.3, carbs: 9, calories: 43.2, fiber: 3.8, sugar: 2.2, sodium: 25 },
    servings: [
      { label: "44g (half serving)", grams: 44 },
      { label: "1 cup (88g)", grams: 88, isDefault: true },
      { label: "132g (1½ servings)", grams: 132 },
      { label: "176g (double)", grams: 176 },
    ],
  },
  {
    name: "Asparagus, raw",
    category: "vegetables",
    per100g: { protein: 2.2, fat: 0.1, carbs: 3.9, calories: 20.1, fiber: 2.1, sugar: 1.9, sodium: 2.2 },
    servings: [
      { label: "67g (half serving)", grams: 67 },
      { label: "1 cup (134g)", grams: 134, isDefault: true },
      { label: "201g (1½ servings)", grams: 201 },
      { label: "268g (double)", grams: 268 },
    ],
  },
  {
    name: "Zucchini, raw",
    category: "vegetables",
    per100g: { protein: 1.2, fat: 0.3, carbs: 3.1, calories: 16.9, fiber: 1, sugar: 2.5, sodium: 9.7 },
    servings: [
      { label: "62g (half serving)", grams: 62 },
      { label: "1 cup chopped (124g)", grams: 124, isDefault: true },
      { label: "186g (1½ servings)", grams: 186 },
      { label: "248g (double)", grams: 248 },
    ],
  },
  {
    name: "Onion, yellow",
    category: "vegetables",
    per100g: { protein: 1.1, fat: 0.1, carbs: 9.4, calories: 40, fiber: 1.7, sugar: 4.3, sodium: 3.6 },
    servings: [
      { label: "55g (half serving)", grams: 55 },
      { label: "1 medium (110g)", grams: 110, isDefault: true },
      { label: "165g (1½ servings)", grams: 165 },
      { label: "220g (double)", grams: 220 },
    ],
  },
  {
    name: "Garlic, raw",
    category: "vegetables",
    per100g: { protein: 6.7, fat: 0, carbs: 33.3, calories: 133.3, fiber: 3.3, sugar: 0, sodium: 0 },
    servings: [
      { label: "2g (half serving)", grams: 2 },
      { label: "1 clove (3g)", grams: 3, isDefault: true },
      { label: "5g (1½ servings)", grams: 5 },
      { label: "6g (double)", grams: 6 },
    ],
  },
  {
    name: "Sweet potato, baked",
    category: "vegetables",
    per100g: { protein: 2, fat: 0.2, carbs: 20.7, calories: 90.4, fiber: 3.3, sugar: 6.5, sodium: 36 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "1 medium (114g)", grams: 114, isDefault: true },
      { label: "171g (1½ servings)", grams: 171 },
      { label: "228g (double)", grams: 228 },
    ],
  },
  {
    name: "Potato, russet, baked",
    category: "vegetables",
    per100g: { protein: 2.7, fat: 0.1, carbs: 21.4, calories: 97.1, fiber: 2.3, sugar: 1, sodium: 13.9 },
    servings: [
      { label: "87g (half serving)", grams: 87 },
      { label: "1 medium (173g)", grams: 173, isDefault: true },
      { label: "260g (1½ servings)", grams: 260 },
      { label: "346g (double)", grams: 346 },
    ],
  },
  {
    name: "Mushroom, white",
    category: "vegetables",
    per100g: { protein: 3.1, fat: 0.3, carbs: 3.3, calories: 21.4, fiber: 1, sugar: 2, sodium: 5.7 },
    servings: [
      { label: "35g (half serving)", grams: 35 },
      { label: "1 cup sliced (70g)", grams: 70, isDefault: true },
      { label: "105g (1½ servings)", grams: 105 },
      { label: "140g (double)", grams: 140 },
    ],
  },
  {
    name: "Cabbage, raw",
    category: "vegetables",
    per100g: { protein: 1.2, fat: 0.1, carbs: 5.8, calories: 24.7, fiber: 2.5, sugar: 3.3, sodium: 18 },
    servings: [
      { label: "45g (half serving)", grams: 45 },
      { label: "1 cup shredded (89g)", grams: 89, isDefault: true },
      { label: "134g (1½ servings)", grams: 134 },
      { label: "178g (double)", grams: 178 },
    ],
  },
  {
    name: "Eggplant, raw",
    category: "vegetables",
    per100g: { protein: 1, fat: 0.2, carbs: 5.9, calories: 24.4, fiber: 3, sugar: 3.5, sodium: 2.4 },
    servings: [
      { label: "41g (half serving)", grams: 41 },
      { label: "1 cup cubed (82g)", grams: 82, isDefault: true },
      { label: "123g (1½ servings)", grams: 123 },
      { label: "164g (double)", grams: 164 },
    ],
  },
  {
    name: "Green beans, raw",
    category: "vegetables",
    per100g: { protein: 1.8, fat: 0.2, carbs: 7, calories: 31, fiber: 2.7, sugar: 3.3, sodium: 6 },
    servings: [
      { label: "50g (half serving)", grams: 50 },
      { label: "1 cup (100g)", grams: 100, isDefault: true },
      { label: "150g (1½ servings)", grams: 150 },
      { label: "200g (double)", grams: 200 },
    ],
  },
  {
    name: "Peas, green, cooked",
    category: "vegetables",
    per100g: { protein: 5.4, fat: 0.3, carbs: 15.6, calories: 83.8, fiber: 5.5, sugar: 5.9, sodium: 3.1 },
    servings: [
      { label: "80g (half serving)", grams: 80 },
      { label: "1 cup (160g)", grams: 160, isDefault: true },
      { label: "240g (1½ servings)", grams: 240 },
      { label: "320g (double)", grams: 320 },
    ],
  },
  {
    name: "Corn, sweet, cooked",
    category: "vegetables",
    per100g: { protein: 3.3, fat: 1.3, carbs: 19.1, calories: 87.2, fiber: 2.1, sugar: 4.1, sodium: 14 },
    servings: [
      { label: "82g (half serving)", grams: 82 },
      { label: "1 cup kernels (164g)", grams: 164, isDefault: true },
      { label: "246g (1½ servings)", grams: 246 },
      { label: "328g (double)", grams: 328 },
    ],
  },
  {
    name: "Beets, raw",
    category: "vegetables",
    per100g: { protein: 1.6, fat: 0.1, carbs: 9.6, calories: 42.6, fiber: 2.8, sugar: 6.8, sodium: 77.9 },
    servings: [
      { label: "68g (half serving)", grams: 68 },
      { label: "1 cup (136g)", grams: 136, isDefault: true },
      { label: "204g (1½ servings)", grams: 204 },
      { label: "272g (double)", grams: 272 },
    ],
  },
  {
    name: "Radish, raw",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.1, carbs: 3.4, calories: 16.4, fiber: 1.6, sugar: 1.9, sodium: 38.8 },
    servings: [
      { label: "58g (half serving)", grams: 58 },
      { label: "1 cup sliced (116g)", grams: 116, isDefault: true },
      { label: "174g (1½ servings)", grams: 174 },
      { label: "232g (double)", grams: 232 },
    ],
  },
  {
    name: "Squash, butternut, baked",
    category: "vegetables",
    per100g: { protein: 0.9, fat: 0.1, carbs: 10.5, calories: 40, fiber: 3.2, sugar: 2, sodium: 3.9 },
    servings: [
      { label: "103g (half serving)", grams: 103 },
      { label: "1 cup cubed (205g)", grams: 205, isDefault: true },
      { label: "308g (1½ servings)", grams: 308 },
      { label: "410g (double)", grams: 410 },
    ],
  },
  {
    name: "Squash, acorn, baked",
    category: "vegetables",
    per100g: { protein: 1.1, fat: 0.1, carbs: 14.6, calories: 56.1, fiber: 4.4, sugar: 0, sodium: 3.9 },
    servings: [
      { label: "103g (half serving)", grams: 103 },
      { label: "1 cup cubed (205g)", grams: 205, isDefault: true },
      { label: "308g (1½ servings)", grams: 308 },
      { label: "410g (double)", grams: 410 },
    ],
  },
  {
    name: "Pumpkin, cooked",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.1, carbs: 4.9, calories: 20, fiber: 1.1, sugar: 2.1, sodium: 0.8 },
    servings: [
      { label: "123g (half serving)", grams: 123 },
      { label: "1 cup (245g)", grams: 245, isDefault: true },
      { label: "368g (1½ servings)", grams: 368 },
      { label: "490g (double)", grams: 490 },
    ],
  },
  {
    name: "Artichoke, cooked",
    category: "vegetables",
    per100g: { protein: 2.9, fat: 0.3, carbs: 12, calories: 53.3, fiber: 5.8, sugar: 1, sodium: 60 },
    servings: [
      { label: "60g (half serving)", grams: 60 },
      { label: "1 medium (120g)", grams: 120, isDefault: true },
      { label: "180g (1½ servings)", grams: 180 },
      { label: "240g (double)", grams: 240 },
    ],
  },
  {
    name: "Bok choy, raw",
    category: "vegetables",
    per100g: { protein: 1.6, fat: 0.1, carbs: 2.1, calories: 12.9, fiber: 1, sugar: 1.1, sodium: 65.7 },
    servings: [
      { label: "35g (half serving)", grams: 35 },
      { label: "1 cup shredded (70g)", grams: 70, isDefault: true },
      { label: "105g (1½ servings)", grams: 105 },
      { label: "140g (double)", grams: 140 },
    ],
  },
  {
    name: "Arugula, raw",
    category: "vegetables",
    per100g: { protein: 2.5, fat: 0.5, carbs: 3.5, calories: 25, fiber: 1.5, sugar: 2, sodium: 25 },
    servings: [
      { label: "10g (half serving)", grams: 10 },
      { label: "1 cup (20g)", grams: 20, isDefault: true },
      { label: "30g (1½ servings)", grams: 30 },
      { label: "40g (double)", grams: 40 },
    ],
  },
  {
    name: "Swiss chard, raw",
    category: "vegetables",
    per100g: { protein: 1.7, fat: 0.3, carbs: 3.9, calories: 19.4, fiber: 1.7, sugar: 1.1, sodium: 213.9 },
    servings: [
      { label: "18g (half serving)", grams: 18 },
      { label: "1 cup (36g)", grams: 36, isDefault: true },
      { label: "54g (1½ servings)", grams: 54 },
      { label: "72g (double)", grams: 72 },
    ],
  },
  {
    name: "Collard greens, raw",
    category: "vegetables",
    per100g: { protein: 3.1, fat: 0.6, carbs: 5.6, calories: 30.6, fiber: 3.9, sugar: 0.6, sodium: 19.4 },
    servings: [
      { label: "18g (half serving)", grams: 18 },
      { label: "1 cup chopped (36g)", grams: 36, isDefault: true },
      { label: "54g (1½ servings)", grams: 54 },
      { label: "72g (double)", grams: 72 },
    ],
  },
  {
    name: "Leek, raw",
    category: "vegetables",
    per100g: { protein: 1.5, fat: 0.3, carbs: 14.2, calories: 60.7, fiber: 1.8, sugar: 3.9, sodium: 20.2 },
    servings: [
      { label: "45g (half serving)", grams: 45 },
      { label: "1 cup chopped (89g)", grams: 89, isDefault: true },
      { label: "134g (1½ servings)", grams: 134 },
      { label: "178g (double)", grams: 178 },
    ],
  },
  {
    name: "Apple, with skin",
    category: "fruits",
    per100g: { protein: 0.3, fat: 0.2, carbs: 13.8, calories: 52.2, fiber: 2.4, sugar: 10.4, sodium: 1.1 },
    servings: [
      { label: "91g (half serving)", grams: 91 },
      { label: "1 medium (182g)", grams: 182, isDefault: true },
      { label: "273g (1½ servings)", grams: 273 },
      { label: "364g (double)", grams: 364 },
    ],
  },
  {
    name: "Banana",
    category: "fruits",
    per100g: { protein: 1.1, fat: 0.3, carbs: 22.9, calories: 89, fiber: 2.6, sugar: 12.2, sodium: 0.8 },
    servings: [
      { label: "59g (half serving)", grams: 59 },
      { label: "1 medium (118g)", grams: 118, isDefault: true },
      { label: "177g (1½ servings)", grams: 177 },
      { label: "236g (double)", grams: 236 },
    ],
  },
  {
    name: "Orange",
    category: "fruits",
    per100g: { protein: 0.9, fat: 0.2, carbs: 11.8, calories: 47.3, fiber: 2.4, sugar: 9.3, sodium: 0 },
    servings: [
      { label: "66g (half serving)", grams: 66 },
      { label: "1 medium (131g)", grams: 131, isDefault: true },
      { label: "197g (1½ servings)", grams: 197 },
      { label: "262g (double)", grams: 262 },
    ],
  },
  {
    name: "Strawberry",
    category: "fruits",
    per100g: { protein: 0.7, fat: 0.3, carbs: 7.7, calories: 31.9, fiber: 2, sugar: 4.9, sodium: 0.7 },
    servings: [
      { label: "72g (half serving)", grams: 72 },
      { label: "1 cup whole (144g)", grams: 144, isDefault: true },
      { label: "216g (1½ servings)", grams: 216 },
      { label: "288g (double)", grams: 288 },
    ],
  },
  {
    name: "Blueberry",
    category: "fruits",
    per100g: { protein: 0.7, fat: 0.3, carbs: 14.5, calories: 56.8, fiber: 2.4, sugar: 9.9, sodium: 0.7 },
    servings: [
      { label: "74g (half serving)", grams: 74 },
      { label: "1 cup (148g)", grams: 148, isDefault: true },
      { label: "222g (1½ servings)", grams: 222 },
      { label: "296g (double)", grams: 296 },
    ],
  },
  {
    name: "Raspberry",
    category: "fruits",
    per100g: { protein: 1.2, fat: 0.7, carbs: 12, calories: 52, fiber: 6.5, sugar: 4.4, sodium: 0.8 },
    servings: [
      { label: "62g (half serving)", grams: 62 },
      { label: "1 cup (123g)", grams: 123, isDefault: true },
      { label: "185g (1½ servings)", grams: 185 },
      { label: "246g (double)", grams: 246 },
    ],
  },
  {
    name: "Blackberry",
    category: "fruits",
    per100g: { protein: 1.4, fat: 0.5, carbs: 9.6, calories: 43.1, fiber: 5.3, sugar: 4.9, sodium: 0.7 },
    servings: [
      { label: "72g (half serving)", grams: 72 },
      { label: "1 cup (144g)", grams: 144, isDefault: true },
      { label: "216g (1½ servings)", grams: 216 },
      { label: "288g (double)", grams: 288 },
    ],
  },
  {
    name: "Grapes, red or green",
    category: "fruits",
    per100g: { protein: 0.7, fat: 0.1, carbs: 18.1, calories: 68.9, fiber: 0.9, sugar: 15.5, sodium: 2 },
    servings: [
      { label: "76g (half serving)", grams: 76 },
      { label: "1 cup (151g)", grams: 151, isDefault: true },
      { label: "227g (1½ servings)", grams: 227 },
      { label: "302g (double)", grams: 302 },
    ],
  },
  {
    name: "Watermelon",
    category: "fruits",
    per100g: { protein: 0.6, fat: 0.1, carbs: 7.6, calories: 30.3, fiber: 0.4, sugar: 6.2, sodium: 1.3 },
    servings: [
      { label: "76g (half serving)", grams: 76 },
      { label: "1 cup diced (152g)", grams: 152, isDefault: true },
      { label: "228g (1½ servings)", grams: 228 },
      { label: "304g (double)", grams: 304 },
    ],
  },
  {
    name: "Cantaloupe",
    category: "fruits",
    per100g: { protein: 0.8, fat: 0.2, carbs: 8.1, calories: 33.8, fiber: 0.9, sugar: 7.8, sodium: 16.3 },
    servings: [
      { label: "80g (half serving)", grams: 80 },
      { label: "1 cup cubed (160g)", grams: 160, isDefault: true },
      { label: "240g (1½ servings)", grams: 240 },
      { label: "320g (double)", grams: 320 },
    ],
  },
  {
    name: "Honeydew melon",
    category: "fruits",
    per100g: { protein: 0.5, fat: 0.1, carbs: 9.1, calories: 35.9, fiber: 0.8, sugar: 8.1, sodium: 18.2 },
    servings: [
      { label: "85g (half serving)", grams: 85 },
      { label: "1 cup diced (170g)", grams: 170, isDefault: true },
      { label: "255g (1½ servings)", grams: 255 },
      { label: "340g (double)", grams: 340 },
    ],
  },
  {
    name: "Pineapple",
    category: "fruits",
    per100g: { protein: 0.5, fat: 0.1, carbs: 13.2, calories: 49.7, fiber: 1.4, sugar: 9.9, sodium: 1.2 },
    servings: [
      { label: "83g (half serving)", grams: 83 },
      { label: "1 cup chunks (165g)", grams: 165, isDefault: true },
      { label: "248g (1½ servings)", grams: 248 },
      { label: "330g (double)", grams: 330 },
    ],
  },
  {
    name: "Mango",
    category: "fruits",
    per100g: { protein: 0.8, fat: 0.4, carbs: 15, calories: 60, fiber: 1.6, sugar: 13.6, sodium: 1.2 },
    servings: [
      { label: "83g (half serving)", grams: 83 },
      { label: "1 cup sliced (165g)", grams: 165, isDefault: true },
      { label: "248g (1½ servings)", grams: 248 },
      { label: "330g (double)", grams: 330 },
    ],
  },
  {
    name: "Peach",
    category: "fruits",
    per100g: { protein: 0.9, fat: 0.3, carbs: 9.5, calories: 39.3, fiber: 1.5, sugar: 8.4, sodium: 0 },
    servings: [
      { label: "75g (half serving)", grams: 75 },
      { label: "1 medium (150g)", grams: 150, isDefault: true },
      { label: "225g (1½ servings)", grams: 225 },
      { label: "300g (double)", grams: 300 },
    ],
  },
  {
    name: "Plum",
    category: "fruits",
    per100g: { protein: 0.8, fat: 0.3, carbs: 11.4, calories: 45.5, fiber: 1.4, sugar: 10, sodium: 0 },
    servings: [
      { label: "33g (half serving)", grams: 33 },
      { label: "1 medium (66g)", grams: 66, isDefault: true },
      { label: "99g (1½ servings)", grams: 99 },
      { label: "132g (double)", grams: 132 },
    ],
  },
  {
    name: "Pear",
    category: "fruits",
    per100g: { protein: 0.3, fat: 0.1, carbs: 15.2, calories: 56.7, fiber: 3.1, sugar: 9.8, sodium: 1.1 },
    servings: [
      { label: "89g (half serving)", grams: 89 },
      { label: "1 medium (178g)", grams: 178, isDefault: true },
      { label: "267g (1½ servings)", grams: 267 },
      { label: "356g (double)", grams: 356 },
    ],
  },
  {
    name: "Kiwi",
    category: "fruits",
    per100g: { protein: 1.2, fat: 0.6, carbs: 14.6, calories: 60.9, fiber: 3, sugar: 9, sodium: 2.9 },
    servings: [
      { label: "35g (half serving)", grams: 35 },
      { label: "1 medium (69g)", grams: 69, isDefault: true },
      { label: "104g (1½ servings)", grams: 104 },
      { label: "138g (double)", grams: 138 },
    ],
  },
  {
    name: "Cherries, sweet",
    category: "fruits",
    per100g: { protein: 1, fat: 0.2, carbs: 16, calories: 63, fiber: 2.1, sugar: 12.8, sodium: 0 },
    servings: [
      { label: "77g (half serving)", grams: 77 },
      { label: "1 cup (154g)", grams: 154, isDefault: true },
      { label: "231g (1½ servings)", grams: 231 },
      { label: "308g (double)", grams: 308 },
    ],
  },
  {
    name: "Avocado",
    category: "fruits",
    per100g: { protein: 2, fat: 14.7, carbs: 8.5, calories: 160, fiber: 6.5, sugar: 0.7, sodium: 6.7 },
    servings: [
      { label: "75g (half serving)", grams: 75 },
      { label: "1 medium (150g)", grams: 150, isDefault: true },
      { label: "225g (1½ servings)", grams: 225 },
      { label: "300g (double)", grams: 300 },
    ],
  },
  {
    name: "Lemon",
    category: "fruits",
    per100g: { protein: 1, fat: 0.3, carbs: 9.3, calories: 29.3, fiber: 2.8, sugar: 2.6, sodium: 1.7 },
    servings: [
      { label: "29g (half serving)", grams: 29 },
      { label: "1 medium (58g)", grams: 58, isDefault: true },
      { label: "87g (1½ servings)", grams: 87 },
      { label: "116g (double)", grams: 116 },
    ],
  },
  {
    name: "Lime",
    category: "fruits",
    per100g: { protein: 0.7, fat: 0.1, carbs: 10.6, calories: 29.9, fiber: 2.8, sugar: 1.6, sodium: 1.5 },
    servings: [
      { label: "34g (half serving)", grams: 34 },
      { label: "1 medium (67g)", grams: 67, isDefault: true },
      { label: "101g (1½ servings)", grams: 101 },
      { label: "134g (double)", grams: 134 },
    ],
  },
  {
    name: "Grapefruit",
    category: "fruits",
    per100g: { protein: 0.7, fat: 0.2, carbs: 10.7, calories: 42.3, fiber: 1.6, sugar: 6.9, sodium: 0 },
    servings: [
      { label: "62g (half serving)", grams: 62 },
      { label: "1/2 medium (123g)", grams: 123, isDefault: true },
      { label: "185g (1½ servings)", grams: 185 },
      { label: "246g (double)", grams: 246 },
    ],
  },
  {
    name: "Pomegranate seeds",
    category: "fruits",
    per100g: { protein: 1.7, fat: 1.1, carbs: 18.7, calories: 82.8, fiber: 4, sugar: 13.7, sodium: 3.4 },
    servings: [
      { label: "44g (half serving)", grams: 44 },
      { label: "1/2 cup (87g)", grams: 87, isDefault: true },
      { label: "131g (1½ servings)", grams: 131 },
      { label: "174g (double)", grams: 174 },
    ],
  },
  {
    name: "Apricot",
    category: "fruits",
    per100g: { protein: 1.4, fat: 0.3, carbs: 11.1, calories: 48.6, fiber: 2, sugar: 9.1, sodium: 0 },
    servings: [
      { label: "18g (half serving)", grams: 18 },
      { label: "1 medium (35g)", grams: 35, isDefault: true },
      { label: "53g (1½ servings)", grams: 53 },
      { label: "70g (double)", grams: 70 },
    ],
  },
  {
    name: "Nectarine",
    category: "fruits",
    per100g: { protein: 1.1, fat: 0.4, carbs: 10.6, calories: 43.7, fiber: 1.7, sugar: 7.9, sodium: 0 },
    servings: [
      { label: "71g (half serving)", grams: 71 },
      { label: "1 medium (142g)", grams: 142, isDefault: true },
      { label: "213g (1½ servings)", grams: 213 },
      { label: "284g (double)", grams: 284 },
    ],
  },
  {
    name: "Fig, fresh",
    category: "fruits",
    per100g: { protein: 0.8, fat: 0.4, carbs: 19.2, calories: 74, fiber: 2.8, sugar: 16.2, sodium: 2 },
    servings: [
      { label: "25g (half serving)", grams: 25 },
      { label: "1 medium (50g)", grams: 50, isDefault: true },
      { label: "75g (1½ servings)", grams: 75 },
      { label: "100g (double)", grams: 100 },
    ],
  },
  {
    name: "Date, Medjool",
    category: "fruits",
    per100g: { protein: 1.7, fat: 0, carbs: 75, calories: 275, fiber: 6.7, sugar: 66.7, sodium: 0 },
    servings: [
      { label: "12g (half serving)", grams: 12 },
      { label: "1 date pitted (24g)", grams: 24, isDefault: true },
      { label: "36g (1½ servings)", grams: 36 },
      { label: "48g (double)", grams: 48 },
    ],
  },
  {
    name: "Raisins",
    category: "fruits",
    per100g: { protein: 3.2, fat: 0.5, carbs: 79.8, calories: 302.4, fiber: 3.7, sugar: 59.8, sodium: 12.2 },
    servings: [
      { label: "21g (half serving)", grams: 21 },
      { label: "1/4 cup (41g)", grams: 41, isDefault: true },
      { label: "62g (1½ servings)", grams: 62 },
      { label: "82g (double)", grams: 82 },
    ],
  },
  {
    name: "Cranberries, raw",
    category: "fruits",
    per100g: { protein: 0.4, fat: 0.1, carbs: 12.2, calories: 46, fiber: 4.6, sugar: 4, sodium: 2 },
    servings: [
      { label: "50g (half serving)", grams: 50 },
      { label: "1 cup (100g)", grams: 100, isDefault: true },
      { label: "150g (1½ servings)", grams: 150 },
      { label: "200g (double)", grams: 200 },
    ],
  },
  {
    name: "Papaya",
    category: "fruits",
    per100g: { protein: 0.5, fat: 0.3, carbs: 10.8, calories: 42.8, fiber: 1.7, sugar: 7.8, sodium: 8.3 },
    servings: [
      { label: "73g (half serving)", grams: 73 },
      { label: "1 cup cubed (145g)", grams: 145, isDefault: true },
      { label: "218g (1½ servings)", grams: 218 },
      { label: "290g (double)", grams: 290 },
    ],
  },
  {
    name: "Chicken breast, skinless",
    category: "protein",
    per100g: { protein: 31.1, fat: 3.5, carbs: 0, calories: 165.5, fiber: 0, sugar: 0, sodium: 74.3 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Chicken thigh, skinless",
    category: "protein",
    per100g: { protein: 23.4, fat: 9.6, carbs: 0, calories: 185, fiber: 0, sugar: 0, sodium: 84.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Turkey breast, skinless",
    category: "protein",
    per100g: { protein: 29.9, fat: 0.7, carbs: 0, calories: 135.4, fiber: 0, sugar: 0, sodium: 57.5 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Ground turkey, 93% lean",
    category: "protein",
    per100g: { protein: 23.9, fat: 8.8, carbs: 0, calories: 177, fiber: 0, sugar: 0, sodium: 75.2 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Ground beef, 85% lean",
    category: "protein",
    per100g: { protein: 19.9, fat: 14.2, carbs: 0, calories: 212.4, fiber: 0, sugar: 0, sodium: 68.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Ground beef, 93% lean",
    category: "protein",
    per100g: { protein: 21.8, fat: 8, carbs: 0, calories: 162.8, fiber: 0, sugar: 0, sodium: 64.6 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Beef sirloin steak",
    category: "protein",
    per100g: { protein: 26.7, fat: 7.7, carbs: 0, calories: 183.2, fiber: 0, sugar: 0, sodium: 54 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Beef ribeye",
    category: "protein",
    per100g: { protein: 22.1, fat: 20, carbs: 0, calories: 274.3, fiber: 0, sugar: 0, sodium: 61.9 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Beef tenderloin",
    category: "protein",
    per100g: { protein: 23.7, fat: 11.1, carbs: 0, calories: 200.9, fiber: 0, sugar: 0, sodium: 54.9 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Pork tenderloin",
    category: "protein",
    per100g: { protein: 25.1, fat: 4.2, carbs: 0, calories: 146, fiber: 0, sugar: 0, sodium: 55.8 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Pork chop, loin",
    category: "protein",
    per100g: { protein: 25.6, fat: 10.5, carbs: 0, calories: 203.5, fiber: 0, sugar: 0, sodium: 54.9 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Bacon, pan fried",
    category: "protein",
    per100g: { protein: 38.8, fat: 41.3, carbs: 1.3, calories: 537.5, fiber: 0, sugar: 0, sodium: 2312.5 },
    servings: [
      { label: "8g (half serving)", grams: 8 },
      { label: "2 slices (16g)", grams: 16, isDefault: true },
      { label: "24g (1½ servings)", grams: 24 },
      { label: "32g (double)", grams: 32 },
    ],
  },
  {
    name: "Ham, deli sliced",
    category: "protein",
    per100g: { protein: 17, fat: 3, carbs: 2.5, calories: 105.3, fiber: 0, sugar: 1.2, sodium: 1298.2 },
    servings: [
      { label: "29g (half serving)", grams: 29 },
      { label: "2 oz (57g)", grams: 57, isDefault: true },
      { label: "86g (1½ servings)", grams: 86 },
      { label: "114g (double)", grams: 114 },
    ],
  },
  {
    name: "Lamb chop, loin",
    category: "protein",
    per100g: { protein: 21.9, fat: 17.3, carbs: 0, calories: 247.8, fiber: 0, sugar: 0, sodium: 75.2 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Lamb leg, roasted",
    category: "protein",
    per100g: { protein: 26.7, fat: 10.3, carbs: 0, calories: 208, fiber: 0, sugar: 0, sodium: 68.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Veal loin",
    category: "protein",
    per100g: { protein: 25.2, fat: 7.5, carbs: 0, calories: 176.1, fiber: 0, sugar: 0, sodium: 82.3 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Bison, ground",
    category: "protein",
    per100g: { protein: 23.3, fat: 8.8, carbs: 0, calories: 177.9, fiber: 0, sugar: 0, sodium: 65.5 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Duck breast, skinless",
    category: "protein",
    per100g: { protein: 23.2, fat: 4.9, carbs: 0, calories: 139.8, fiber: 0, sugar: 0, sodium: 86.7 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Liver, beef, cooked",
    category: "protein",
    per100g: { protein: 28.9, fat: 5.2, carbs: 5.2, calories: 190.6, fiber: 0, sugar: 0, sodium: 89.4 },
    servings: [
      { label: "43g (half serving)", grams: 43 },
      { label: "3 oz (85g)", grams: 85, isDefault: true },
      { label: "128g (1½ servings)", grams: 128 },
      { label: "170g (double)", grams: 170 },
    ],
  },
  {
    name: "Sausage, pork",
    category: "protein",
    per100g: { protein: 18.9, fat: 28.5, carbs: 1.5, calories: 340.7, fiber: 0, sugar: 1.5, sodium: 774.1 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 link (cooked) (27g)", grams: 27, isDefault: true },
      { label: "41g (1½ servings)", grams: 41 },
      { label: "54g (double)", grams: 54 },
    ],
  },
  {
    name: "Salmon, Atlantic, cooked",
    category: "protein",
    per100g: { protein: 22, fat: 12.4, carbs: 0, calories: 206.2, fiber: 0, sugar: 0, sodium: 65.5 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Tuna, ahi (yellowfin)",
    category: "protein",
    per100g: { protein: 28.5, fat: 1.2, carbs: 0, calories: 130.1, fiber: 0, sugar: 0, sodium: 45.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Tuna, canned in water",
    category: "protein",
    per100g: { protein: 19.4, fat: 0.9, carbs: 0, calories: 85.9, fiber: 0, sugar: 0, sodium: 290.6 },
    servings: [
      { label: "43g (half serving)", grams: 43 },
      { label: "1 can drained (85g)", grams: 85, isDefault: true },
      { label: "128g (1½ servings)", grams: 128 },
      { label: "170g (double)", grams: 170 },
    ],
  },
  {
    name: "Cod, Atlantic, cooked",
    category: "protein",
    per100g: { protein: 23, fat: 0.9, carbs: 0, calories: 105.3, fiber: 0, sugar: 0, sodium: 77 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Tilapia, cooked",
    category: "protein",
    per100g: { protein: 26.5, fat: 2.7, carbs: 0, calories: 128.3, fiber: 0, sugar: 0, sodium: 57.5 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Halibut, cooked",
    category: "protein",
    per100g: { protein: 26.5, fat: 3.1, carbs: 0, calories: 137.2, fiber: 0, sugar: 0, sodium: 79.6 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Shrimp, cooked",
    category: "protein",
    per100g: { protein: 20.2, fat: 1.5, carbs: 1.3, calories: 106.2, fiber: 0, sugar: 0, sodium: 558.4 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Crab, Alaskan king",
    category: "protein",
    per100g: { protein: 19.1, fat: 1.5, carbs: 0, calories: 97.3, fiber: 0, sugar: 0, sodium: 1076.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Lobster, cooked",
    category: "protein",
    per100g: { protein: 18.3, fat: 0.8, carbs: 1.2, calories: 86.7, fiber: 0, sugar: 0, sodium: 488.5 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Scallops, cooked",
    category: "protein",
    per100g: { protein: 21.2, fat: 0.9, carbs: 5.3, calories: 112.4, fiber: 0, sugar: 0, sodium: 659.3 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Sardines, canned in oil",
    category: "protein",
    per100g: { protein: 24.7, fat: 11.4, carbs: 0, calories: 207.6, fiber: 0, sugar: 0, sodium: 505.4 },
    servings: [
      { label: "46g (half serving)", grams: 46 },
      { label: "1 can drained (92g)", grams: 92, isDefault: true },
      { label: "138g (1½ servings)", grams: 138 },
      { label: "184g (double)", grams: 184 },
    ],
  },
  {
    name: "Mackerel, Atlantic, cooked",
    category: "protein",
    per100g: { protein: 23.9, fat: 17.9, carbs: 0, calories: 262.8, fiber: 0, sugar: 0, sodium: 83.2 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Trout, rainbow, cooked",
    category: "protein",
    per100g: { protein: 24.8, fat: 7.1, carbs: 0, calories: 172.6, fiber: 0, sugar: 0, sodium: 53.1 },
    servings: [
      { label: "57g (half serving)", grams: 57 },
      { label: "4 oz cooked (113g)", grams: 113, isDefault: true },
      { label: "170g (1½ servings)", grams: 170 },
      { label: "226g (double)", grams: 226 },
    ],
  },
  {
    name: "Anchovy, canned in oil",
    category: "protein",
    per100g: { protein: 29, fat: 9.5, carbs: 0, calories: 210, fiber: 0, sugar: 0, sodium: 3670 },
    servings: [
      { label: "10g (half serving)", grams: 10 },
      { label: "5 anchovies (20g)", grams: 20, isDefault: true },
      { label: "30g (1½ servings)", grams: 30 },
      { label: "40g (double)", grams: 40 },
    ],
  },
  {
    name: "Mussels, cooked",
    category: "protein",
    per100g: { protein: 23.8, fat: 4.5, carbs: 7.4, calories: 171.8, fiber: 0, sugar: 0, sodium: 369.4 },
    servings: [
      { label: "43g (half serving)", grams: 43 },
      { label: "3 oz cooked (85g)", grams: 85, isDefault: true },
      { label: "128g (1½ servings)", grams: 128 },
      { label: "170g (double)", grams: 170 },
    ],
  },
  {
    name: "Milk, whole (3.25%)",
    category: "dairy",
    per100g: { protein: 3.2, fat: 3.3, carbs: 4.8, calories: 61.1, fiber: 0, sugar: 5, sodium: 43 },
    servings: [
      { label: "122g (half serving)", grams: 122 },
      { label: "1 cup (244g)", grams: 244, isDefault: true },
      { label: "366g (1½ servings)", grams: 366 },
      { label: "488g (double)", grams: 488 },
    ],
  },
  {
    name: "Milk, 2%",
    category: "dairy",
    per100g: { protein: 3.3, fat: 2, carbs: 4.8, calories: 50, fiber: 0, sugar: 5, sodium: 47.1 },
    servings: [
      { label: "122g (half serving)", grams: 122 },
      { label: "1 cup (244g)", grams: 244, isDefault: true },
      { label: "366g (1½ servings)", grams: 366 },
      { label: "488g (double)", grams: 488 },
    ],
  },
  {
    name: "Milk, skim (nonfat)",
    category: "dairy",
    per100g: { protein: 3.4, fat: 0.1, carbs: 5, calories: 33.9, fiber: 0, sugar: 5.1, sodium: 42 },
    servings: [
      { label: "123g (half serving)", grams: 123 },
      { label: "1 cup (245g)", grams: 245, isDefault: true },
      { label: "368g (1½ servings)", grams: 368 },
      { label: "490g (double)", grams: 490 },
    ],
  },
  {
    name: "Greek yogurt, plain, nonfat",
    category: "dairy",
    per100g: { protein: 10.1, fat: 0.3, carbs: 4, calories: 57.3, fiber: 0, sugar: 4, sodium: 37.4 },
    servings: [
      { label: "114g (half serving)", grams: 114 },
      { label: "1 cup (8 oz) (227g)", grams: 227, isDefault: true },
      { label: "341g (1½ servings)", grams: 341 },
      { label: "454g (double)", grams: 454 },
    ],
  },
  {
    name: "Yogurt, plain, whole milk",
    category: "dairy",
    per100g: { protein: 3.5, fat: 3.3, carbs: 4.7, calories: 60.8, fiber: 0, sugar: 4.7, sodium: 46.1 },
    servings: [
      { label: "123g (half serving)", grams: 123 },
      { label: "1 cup (8 oz) (245g)", grams: 245, isDefault: true },
      { label: "368g (1½ servings)", grams: 368 },
      { label: "490g (double)", grams: 490 },
    ],
  },
  {
    name: "Cottage cheese, low-fat",
    category: "dairy",
    per100g: { protein: 12.4, fat: 1, carbs: 2.7, calories: 72.1, fiber: 0, sugar: 2.7, sodium: 406.2 },
    servings: [
      { label: "113g (half serving)", grams: 113 },
      { label: "1 cup (226g)", grams: 226, isDefault: true },
      { label: "339g (1½ servings)", grams: 339 },
      { label: "452g (double)", grams: 452 },
    ],
  },
  {
    name: "Cheddar cheese",
    category: "dairy",
    per100g: { protein: 23.2, fat: 33.9, carbs: 1.4, calories: 410.7, fiber: 0, sugar: 0.4, sodium: 657.1 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Mozzarella cheese, part-skim",
    category: "dairy",
    per100g: { protein: 24.6, fat: 16.1, carbs: 2.9, calories: 257.1, fiber: 0, sugar: 1.1, sodium: 625 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Parmesan cheese, grated",
    category: "dairy",
    per100g: { protein: 28, fat: 28, carbs: 14, calories: 420, fiber: 0, sugar: 0, sodium: 1520 },
    servings: [
      { label: "3g (half serving)", grams: 3 },
      { label: "1 tbsp (5g)", grams: 5, isDefault: true },
      { label: "8g (1½ servings)", grams: 8 },
      { label: "10g (double)", grams: 10 },
    ],
  },
  {
    name: "Feta cheese",
    category: "dairy",
    per100g: { protein: 14.3, fat: 21.4, carbs: 4.3, calories: 264.3, fiber: 0, sugar: 4.3, sodium: 1128.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Cream cheese",
    category: "dairy",
    per100g: { protein: 6.4, fat: 35, carbs: 5.7, calories: 357.1, fiber: 0, sugar: 2.9, sodium: 328.6 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Butter, salted",
    category: "dairy",
    per100g: { protein: 0.7, fat: 82.1, carbs: 0, calories: 728.6, fiber: 0, sugar: 0, sodium: 650 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Heavy cream",
    category: "dairy",
    per100g: { protein: 2.7, fat: 36, carbs: 2.7, calories: 340, fiber: 0, sugar: 2.7, sodium: 40 },
    servings: [
      { label: "8g (half serving)", grams: 8 },
      { label: "1 tbsp (15g)", grams: 15, isDefault: true },
      { label: "23g (1½ servings)", grams: 23 },
      { label: "30g (double)", grams: 30 },
    ],
  },
  {
    name: "Egg, whole, large",
    category: "dairy",
    per100g: { protein: 12.6, fat: 9.6, carbs: 0.8, calories: 144, fiber: 0, sugar: 0.8, sodium: 142 },
    servings: [
      { label: "25g (half serving)", grams: 25 },
      { label: "1 large (50g)", grams: 50, isDefault: true },
      { label: "75g (1½ servings)", grams: 75 },
      { label: "100g (double)", grams: 100 },
    ],
  },
  {
    name: "Egg whites",
    category: "dairy",
    per100g: { protein: 10.9, fat: 0.3, carbs: 0.6, calories: 51.5, fiber: 0, sugar: 0.6, sodium: 166.7 },
    servings: [
      { label: "17g (half serving)", grams: 17 },
      { label: "1 large (33g)", grams: 33, isDefault: true },
      { label: "50g (1½ servings)", grams: 50 },
      { label: "66g (double)", grams: 66 },
    ],
  },
  {
    name: "Brown rice, cooked",
    category: "grains",
    per100g: { protein: 2.3, fat: 0.8, carbs: 23.5, calories: 111.8, fiber: 1.8, sugar: 0.4, sodium: 5.1 },
    servings: [
      { label: "98g (half serving)", grams: 98 },
      { label: "1 cup (195g)", grams: 195, isDefault: true },
      { label: "293g (1½ servings)", grams: 293 },
      { label: "390g (double)", grams: 390 },
    ],
  },
  {
    name: "White rice, cooked",
    category: "grains",
    per100g: { protein: 2.7, fat: 0.3, carbs: 28.2, calories: 129.7, fiber: 0.4, sugar: 0.1, sodium: 1.3 },
    servings: [
      { label: "79g (half serving)", grams: 79 },
      { label: "1 cup (158g)", grams: 158, isDefault: true },
      { label: "237g (1½ servings)", grams: 237 },
      { label: "316g (double)", grams: 316 },
    ],
  },
  {
    name: "Quinoa, cooked",
    category: "grains",
    per100g: { protein: 4.4, fat: 1.9, carbs: 21.3, calories: 120, fiber: 2.8, sugar: 0.9, sodium: 7 },
    servings: [
      { label: "93g (half serving)", grams: 93 },
      { label: "1 cup (185g)", grams: 185, isDefault: true },
      { label: "278g (1½ servings)", grams: 278 },
      { label: "370g (double)", grams: 370 },
    ],
  },
  {
    name: "Oats, rolled, dry",
    category: "grains",
    per100g: { protein: 13.3, fat: 6.8, carbs: 68.5, calories: 385, fiber: 10.3, sugar: 1, sodium: 5 },
    servings: [
      { label: "20g (half serving)", grams: 20 },
      { label: "1/2 cup dry (40g)", grams: 40, isDefault: true },
      { label: "60g (1½ servings)", grams: 60 },
      { label: "80g (double)", grams: 80 },
    ],
  },
  {
    name: "Oatmeal, cooked",
    category: "grains",
    per100g: { protein: 2.5, fat: 1.5, carbs: 12, calories: 70.9, fiber: 1.7, sugar: 0.3, sodium: 3.8 },
    servings: [
      { label: "117g (half serving)", grams: 117 },
      { label: "1 cup (234g)", grams: 234, isDefault: true },
      { label: "351g (1½ servings)", grams: 351 },
      { label: "468g (double)", grams: 468 },
    ],
  },
  {
    name: "Barley, pearled, cooked",
    category: "grains",
    per100g: { protein: 2.3, fat: 0.4, carbs: 28.2, calories: 122.9, fiber: 3.8, sugar: 0.3, sodium: 3.2 },
    servings: [
      { label: "79g (half serving)", grams: 79 },
      { label: "1 cup (157g)", grams: 157, isDefault: true },
      { label: "236g (1½ servings)", grams: 236 },
      { label: "314g (double)", grams: 314 },
    ],
  },
  {
    name: "Buckwheat, cooked",
    category: "grains",
    per100g: { protein: 3.4, fat: 0.6, carbs: 19.9, calories: 92.3, fiber: 2.7, sugar: 0.9, sodium: 4.2 },
    servings: [
      { label: "84g (half serving)", grams: 84 },
      { label: "1 cup (168g)", grams: 168, isDefault: true },
      { label: "252g (1½ servings)", grams: 252 },
      { label: "336g (double)", grams: 336 },
    ],
  },
  {
    name: "Bulgur, cooked",
    category: "grains",
    per100g: { protein: 3.1, fat: 0.2, carbs: 18.6, calories: 83, fiber: 4.5, sugar: 0.1, sodium: 4.9 },
    servings: [
      { label: "91g (half serving)", grams: 91 },
      { label: "1 cup (182g)", grams: 182, isDefault: true },
      { label: "273g (1½ servings)", grams: 273 },
      { label: "364g (double)", grams: 364 },
    ],
  },
  {
    name: "Farro, cooked",
    category: "grains",
    per100g: { protein: 4.1, fat: 0.6, carbs: 27.6, calories: 129.4, fiber: 2.9, sugar: 0, sodium: 4.7 },
    servings: [
      { label: "85g (half serving)", grams: 85 },
      { label: "1 cup (170g)", grams: 170, isDefault: true },
      { label: "255g (1½ servings)", grams: 255 },
      { label: "340g (double)", grams: 340 },
    ],
  },
  {
    name: "Millet, cooked",
    category: "grains",
    per100g: { protein: 3.5, fat: 1, carbs: 23.7, calories: 119, fiber: 1.3, sugar: 0.1, sodium: 1.7 },
    servings: [
      { label: "87g (half serving)", grams: 87 },
      { label: "1 cup (174g)", grams: 174, isDefault: true },
      { label: "261g (1½ servings)", grams: 261 },
      { label: "348g (double)", grams: 348 },
    ],
  },
  {
    name: "Whole wheat bread",
    category: "grains",
    per100g: { protein: 12.2, fat: 3.4, carbs: 42.8, calories: 253.1, fiber: 5.9, sugar: 4.4, sodium: 450 },
    servings: [
      { label: "16g (half serving)", grams: 16 },
      { label: "1 slice (32g)", grams: 32, isDefault: true },
      { label: "48g (1½ servings)", grams: 48 },
      { label: "64g (double)", grams: 64 },
    ],
  },
  {
    name: "White bread",
    category: "grains",
    per100g: { protein: 9, fat: 3.4, carbs: 49.3, calories: 265.5, fiber: 2.8, sugar: 4.8, sodium: 489.7 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "1 slice (29g)", grams: 29, isDefault: true },
      { label: "44g (1½ servings)", grams: 44 },
      { label: "58g (double)", grams: 58 },
    ],
  },
  {
    name: "Pasta, whole wheat, cooked",
    category: "grains",
    per100g: { protein: 5.4, fat: 0.6, carbs: 26.6, calories: 124.3, fiber: 4.5, sugar: 0.8, sodium: 2.9 },
    servings: [
      { label: "70g (half serving)", grams: 70 },
      { label: "1 cup (140g)", grams: 140, isDefault: true },
      { label: "210g (1½ servings)", grams: 210 },
      { label: "280g (double)", grams: 280 },
    ],
  },
  {
    name: "Pasta, regular, cooked",
    category: "grains",
    per100g: { protein: 5.8, fat: 0.9, carbs: 30.9, calories: 157.1, fiber: 1.8, sugar: 0.6, sodium: 0.7 },
    servings: [
      { label: "70g (half serving)", grams: 70 },
      { label: "1 cup (140g)", grams: 140, isDefault: true },
      { label: "210g (1½ servings)", grams: 210 },
      { label: "280g (double)", grams: 280 },
    ],
  },
  {
    name: "Couscous, cooked",
    category: "grains",
    per100g: { protein: 3.8, fat: 0.2, carbs: 23.2, calories: 112.1, fiber: 1.4, sugar: 0.1, sodium: 5.1 },
    servings: [
      { label: "79g (half serving)", grams: 79 },
      { label: "1 cup (157g)", grams: 157, isDefault: true },
      { label: "236g (1½ servings)", grams: 236 },
      { label: "314g (double)", grams: 314 },
    ],
  },
  {
    name: "Cornmeal, dry",
    category: "grains",
    per100g: { protein: 8.5, fat: 3.6, carbs: 78.7, calories: 369.2, fiber: 7.4, sugar: 0.8, sodium: 5.1 },
    servings: [
      { label: "20g (half serving)", grams: 20 },
      { label: "1/4 cup (39g)", grams: 39, isDefault: true },
      { label: "59g (1½ servings)", grams: 59 },
      { label: "78g (double)", grams: 78 },
    ],
  },
  {
    name: "Wild rice, cooked",
    category: "grains",
    per100g: { protein: 4, fat: 0.4, carbs: 21.3, calories: 101.2, fiber: 1.8, sugar: 0.7, sodium: 3 },
    servings: [
      { label: "82g (half serving)", grams: 82 },
      { label: "1 cup (164g)", grams: 164, isDefault: true },
      { label: "246g (1½ servings)", grams: 246 },
      { label: "328g (double)", grams: 328 },
    ],
  },
  {
    name: "Rye bread",
    category: "grains",
    per100g: { protein: 8.4, fat: 3.4, carbs: 48.4, calories: 259.4, fiber: 5.9, sugar: 3.8, sodium: 659.4 },
    servings: [
      { label: "16g (half serving)", grams: 16 },
      { label: "1 slice (32g)", grams: 32, isDefault: true },
      { label: "48g (1½ servings)", grams: 48 },
      { label: "64g (double)", grams: 64 },
    ],
  },
  {
    name: "Tortilla, corn",
    category: "grains",
    per100g: { protein: 5.8, fat: 2.7, carbs: 46.5, calories: 223.1, fiber: 5.4, sugar: 0.8, sodium: 11.5 },
    servings: [
      { label: "13g (half serving)", grams: 13 },
      { label: "1 tortilla (6 in) (26g)", grams: 26, isDefault: true },
      { label: "39g (1½ servings)", grams: 39 },
      { label: "52g (double)", grams: 52 },
    ],
  },
  {
    name: "Tortilla, flour",
    category: "grains",
    per100g: { protein: 7.6, fat: 7.6, carbs: 49.6, calories: 293.9, fiber: 2.9, sugar: 2, sodium: 810.2 },
    servings: [
      { label: "25g (half serving)", grams: 25 },
      { label: "1 tortilla (8 in) (49g)", grams: 49, isDefault: true },
      { label: "74g (1½ servings)", grams: 74 },
      { label: "98g (double)", grams: 98 },
    ],
  },
  {
    name: "Black beans, cooked",
    category: "grains",
    per100g: { protein: 8.8, fat: 0.5, carbs: 23.7, calories: 132, fiber: 8.7, sugar: 0.3, sodium: 1.2 },
    servings: [
      { label: "86g (half serving)", grams: 86 },
      { label: "1 cup (172g)", grams: 172, isDefault: true },
      { label: "258g (1½ servings)", grams: 258 },
      { label: "344g (double)", grams: 344 },
    ],
  },
  {
    name: "Pinto beans, cooked",
    category: "grains",
    per100g: { protein: 9, fat: 0.6, carbs: 26.2, calories: 143.3, fiber: 9, sugar: 0.4, sodium: 1.2 },
    servings: [
      { label: "86g (half serving)", grams: 86 },
      { label: "1 cup (171g)", grams: 171, isDefault: true },
      { label: "257g (1½ servings)", grams: 257 },
      { label: "342g (double)", grams: 342 },
    ],
  },
  {
    name: "Kidney beans, cooked",
    category: "grains",
    per100g: { protein: 8.6, fat: 0.5, carbs: 22.8, calories: 127.1, fiber: 7.4, sugar: 0.3, sodium: 1.1 },
    servings: [
      { label: "89g (half serving)", grams: 89 },
      { label: "1 cup (177g)", grams: 177, isDefault: true },
      { label: "266g (1½ servings)", grams: 266 },
      { label: "354g (double)", grams: 354 },
    ],
  },
  {
    name: "Chickpeas (garbanzo), cooked",
    category: "grains",
    per100g: { protein: 8.8, fat: 2.6, carbs: 27.4, calories: 164, fiber: 7.6, sugar: 4.8, sodium: 6.7 },
    servings: [
      { label: "82g (half serving)", grams: 82 },
      { label: "1 cup (164g)", grams: 164, isDefault: true },
      { label: "246g (1½ servings)", grams: 246 },
      { label: "328g (double)", grams: 328 },
    ],
  },
  {
    name: "Lentils, cooked",
    category: "grains",
    per100g: { protein: 9, fat: 0.4, carbs: 20.2, calories: 116.2, fiber: 7.9, sugar: 1.8, sodium: 2 },
    servings: [
      { label: "99g (half serving)", grams: 99 },
      { label: "1 cup (198g)", grams: 198, isDefault: true },
      { label: "297g (1½ servings)", grams: 297 },
      { label: "396g (double)", grams: 396 },
    ],
  },
  {
    name: "Navy beans, cooked",
    category: "grains",
    per100g: { protein: 8.2, fat: 0.6, carbs: 26, calories: 140.1, fiber: 10.5, sugar: 0.4, sodium: 0 },
    servings: [
      { label: "91g (half serving)", grams: 91 },
      { label: "1 cup (182g)", grams: 182, isDefault: true },
      { label: "273g (1½ servings)", grams: 273 },
      { label: "364g (double)", grams: 364 },
    ],
  },
  {
    name: "Lima beans, cooked",
    category: "grains",
    per100g: { protein: 6.8, fat: 0.3, carbs: 23.6, calories: 122.9, fiber: 5.4, sugar: 1.6, sodium: 2.4 },
    servings: [
      { label: "85g (half serving)", grams: 85 },
      { label: "1 cup (170g)", grams: 170, isDefault: true },
      { label: "255g (1½ servings)", grams: 255 },
      { label: "340g (double)", grams: 340 },
    ],
  },
  {
    name: "White beans (cannellini)",
    category: "grains",
    per100g: { protein: 9.7, fat: 0.3, carbs: 25.1, calories: 139.1, fiber: 6.3, sugar: 0.3, sodium: 6.1 },
    servings: [
      { label: "90g (half serving)", grams: 90 },
      { label: "1 cup cooked (179g)", grams: 179, isDefault: true },
      { label: "269g (1½ servings)", grams: 269 },
      { label: "358g (double)", grams: 358 },
    ],
  },
  {
    name: "Edamame (soybeans)",
    category: "grains",
    per100g: { protein: 11.9, fat: 5.2, carbs: 8.9, calories: 121.3, fiber: 5.2, sugar: 2.2, sodium: 5.8 },
    servings: [
      { label: "78g (half serving)", grams: 78 },
      { label: "1 cup shelled (155g)", grams: 155, isDefault: true },
      { label: "233g (1½ servings)", grams: 233 },
      { label: "310g (double)", grams: 310 },
    ],
  },
  {
    name: "Tofu, firm",
    category: "grains",
    per100g: { protein: 17.3, fat: 8.7, carbs: 2.8, calories: 143.7, fiber: 2.3, sugar: 0.7, sodium: 13.5 },
    servings: [
      { label: "63g (half serving)", grams: 63 },
      { label: "1/2 cup (4 oz) (126g)", grams: 126, isDefault: true },
      { label: "189g (1½ servings)", grams: 189 },
      { label: "252g (double)", grams: 252 },
    ],
  },
  {
    name: "Tempeh",
    category: "grains",
    per100g: { protein: 20.5, fat: 10.8, carbs: 9.4, calories: 192.8, fiber: 0, sugar: 0, sodium: 8.4 },
    servings: [
      { label: "42g (half serving)", grams: 42 },
      { label: "1/2 cup (3 oz) (83g)", grams: 83, isDefault: true },
      { label: "125g (1½ servings)", grams: 125 },
      { label: "166g (double)", grams: 166 },
    ],
  },
  {
    name: "Black-eyed peas, cooked",
    category: "grains",
    per100g: { protein: 7.7, fat: 0.5, carbs: 20.8, calories: 115.8, fiber: 6.5, sugar: 3.3, sodium: 4.1 },
    servings: [
      { label: "86g (half serving)", grams: 86 },
      { label: "1 cup (171g)", grams: 171, isDefault: true },
      { label: "257g (1½ servings)", grams: 257 },
      { label: "342g (double)", grams: 342 },
    ],
  },
  {
    name: "Split peas, cooked",
    category: "grains",
    per100g: { protein: 8.3, fat: 0.4, carbs: 21.1, calories: 117.9, fiber: 8.3, sugar: 2.9, sodium: 2 },
    servings: [
      { label: "98g (half serving)", grams: 98 },
      { label: "1 cup (196g)", grams: 196, isDefault: true },
      { label: "294g (1½ servings)", grams: 294 },
      { label: "392g (double)", grams: 392 },
    ],
  },
  {
    name: "Mung beans, cooked",
    category: "grains",
    per100g: { protein: 7, fat: 0.4, carbs: 19.2, calories: 105, fiber: 7.6, sugar: 2, sodium: 2 },
    servings: [
      { label: "101g (half serving)", grams: 101 },
      { label: "1 cup (202g)", grams: 202, isDefault: true },
      { label: "303g (1½ servings)", grams: 303 },
      { label: "404g (double)", grams: 404 },
    ],
  },
  {
    name: "Refried beans, canned",
    category: "grains",
    per100g: { protein: 5.1, fat: 1.1, carbs: 14.6, calories: 86.5, fiber: 4.3, sugar: 0.6, sodium: 384.1 },
    servings: [
      { label: "63g (half serving)", grams: 63 },
      { label: "1/2 cup (126g)", grams: 126, isDefault: true },
      { label: "189g (1½ servings)", grams: 189 },
      { label: "252g (double)", grams: 252 },
    ],
  },
  {
    name: "Almonds, raw",
    category: "nuts",
    per100g: { protein: 21.4, fat: 50.7, carbs: 21.8, calories: 585.7, fiber: 12.5, sugar: 4.3, sodium: 0 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~23 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Walnuts, halves",
    category: "nuts",
    per100g: { protein: 15.4, fat: 66.1, carbs: 13.9, calories: 660.7, fiber: 6.8, sugar: 2.5, sodium: 3.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~14 halves) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Cashews, raw",
    category: "nuts",
    per100g: { protein: 18.6, fat: 44.3, carbs: 30.7, calories: 560.7, fiber: 3.2, sugar: 6.1, sodium: 10.7 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~18 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Pecans, halves",
    category: "nuts",
    per100g: { protein: 9.3, fat: 72.9, carbs: 13.9, calories: 700, fiber: 9.6, sugar: 3.9, sodium: 0 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~19 halves) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Pistachios, shelled",
    category: "nuts",
    per100g: { protein: 20.4, fat: 46.1, carbs: 27.5, calories: 567.9, fiber: 10.4, sugar: 7.9, sodium: 0 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~49 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Brazil nuts",
    category: "nuts",
    per100g: { protein: 14.6, fat: 67.9, carbs: 11.8, calories: 667.9, fiber: 7.5, sugar: 2.5, sodium: 3.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~6 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Macadamia nuts",
    category: "nuts",
    per100g: { protein: 7.9, fat: 76.8, carbs: 13.9, calories: 728.6, fiber: 8.6, sugar: 4.6, sodium: 3.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~10 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Hazelnuts",
    category: "nuts",
    per100g: { protein: 15, fat: 61.4, carbs: 16.8, calories: 635.7, fiber: 9.6, sugar: 4.3, sodium: 0 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~21 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Peanuts, raw",
    category: "nuts",
    per100g: { protein: 26.1, fat: 50, carbs: 16.4, calories: 575, fiber: 8.6, sugar: 4.6, sodium: 17.9 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (~28 nuts) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Pine nuts",
    category: "nuts",
    per100g: { protein: 13.9, fat: 69.3, carbs: 13.2, calories: 682.1, fiber: 3.6, sugar: 3.6, sodium: 3.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Sunflower seeds, hulled",
    category: "nuts",
    per100g: { protein: 19.6, fat: 52.1, carbs: 24.3, calories: 589.3, fiber: 10.7, sugar: 2.5, sodium: 3.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Pumpkin seeds (pepitas)",
    category: "nuts",
    per100g: { protein: 30.7, fat: 50, carbs: 10.7, calories: 564.3, fiber: 6.1, sugar: 1.4, sodium: 17.9 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Chia seeds",
    category: "nuts",
    per100g: { protein: 16.8, fat: 31.1, carbs: 42.5, calories: 492.9, fiber: 35, sugar: 0, sodium: 17.9 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (2 tbsp) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Flax seeds, ground",
    category: "nuts",
    per100g: { protein: 18.6, fat: 42.5, carbs: 29.3, calories: 539.3, fiber: 27.5, sugar: 1.4, sodium: 28.6 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (2 tbsp) (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Sesame seeds",
    category: "nuts",
    per100g: { protein: 17.9, fat: 50.4, carbs: 23.6, calories: 578.6, fiber: 11.8, sugar: 0.7, sodium: 10.7 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Olive oil, extra virgin",
    category: "fats",
    per100g: { protein: 0, fat: 96.4, carbs: 0, calories: 850, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Coconut oil",
    category: "fats",
    per100g: { protein: 0, fat: 97.1, carbs: 0, calories: 835.7, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Avocado oil",
    category: "fats",
    per100g: { protein: 0, fat: 100, carbs: 0, calories: 885.7, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Canola oil",
    category: "fats",
    per100g: { protein: 0, fat: 100, carbs: 0, calories: 885.7, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Vegetable (soybean) oil",
    category: "fats",
    per100g: { protein: 0, fat: 97.1, carbs: 0, calories: 857.1, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Sesame oil",
    category: "fats",
    per100g: { protein: 0, fat: 97.1, carbs: 0, calories: 857.1, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Ghee (clarified butter)",
    category: "fats",
    per100g: { protein: 0, fat: 99.3, carbs: 0, calories: 878.6, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (14g)", grams: 14, isDefault: true },
      { label: "21g (1½ servings)", grams: 21 },
      { label: "28g (double)", grams: 28 },
    ],
  },
  {
    name: "Lard",
    category: "fats",
    per100g: { protein: 0, fat: 98.5, carbs: 0, calories: 884.6, fiber: 0, sugar: 0, sodium: 0 },
    servings: [
      { label: "7g (half serving)", grams: 7 },
      { label: "1 tbsp (13g)", grams: 13, isDefault: true },
      { label: "20g (1½ servings)", grams: 20 },
      { label: "26g (double)", grams: 26 },
    ],
  },
  {
    name: "Whey protein powder",
    category: "protein",
    per100g: { protein: 80, fat: 5, carbs: 10, calories: 400, fiber: 3.3, sugar: 6.7, sodium: 200 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "1 scoop (~30g) (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Casein protein powder",
    category: "protein",
    per100g: { protein: 72.7, fat: 3, carbs: 9.1, calories: 363.6, fiber: 3, sugar: 3, sodium: 606.1 },
    servings: [
      { label: "17g (half serving)", grams: 17 },
      { label: "1 scoop (~33g) (33g)", grams: 33, isDefault: true },
      { label: "50g (1½ servings)", grams: 50 },
      { label: "66g (double)", grams: 66 },
    ],
  },
  {
    name: "Pea protein powder",
    category: "protein",
    per100g: { protein: 80, fat: 5, carbs: 3.3, calories: 366.7, fiber: 3.3, sugar: 3.3, sodium: 833.3 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "1 scoop (~30g) (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Soy protein isolate",
    category: "protein",
    per100g: { protein: 83.3, fat: 3.3, carbs: 3.3, calories: 366.7, fiber: 1.7, sugar: 1.7, sodium: 733.3 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "1 scoop (~30g) (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Collagen peptides",
    category: "protein",
    per100g: { protein: 90, fat: 0, carbs: 0, calories: 350, fiber: 0, sugar: 0, sodium: 250 },
    servings: [
      { label: "10g (half serving)", grams: 10 },
      { label: "1 scoop (~20g) (20g)", grams: 20, isDefault: true },
      { label: "30g (1½ servings)", grams: 30 },
      { label: "40g (double)", grams: 40 },
    ],
  },
  {
    name: "Honey",
    category: "other",
    per100g: { protein: 0.5, fat: 0, carbs: 82.4, calories: 304.8, fiber: 0, sugar: 81.9, sodium: 4.8 },
    servings: [
      { label: "11g (half serving)", grams: 11 },
      { label: "1 tbsp (21g)", grams: 21, isDefault: true },
      { label: "32g (1½ servings)", grams: 32 },
      { label: "42g (double)", grams: 42 },
    ],
  },
  {
    name: "Maple syrup, pure",
    category: "other",
    per100g: { protein: 0, fat: 0.5, carbs: 67, calories: 260, fiber: 0, sugar: 60.5, sodium: 10 },
    servings: [
      { label: "10g (half serving)", grams: 10 },
      { label: "1 tbsp (20g)", grams: 20, isDefault: true },
      { label: "30g (1½ servings)", grams: 30 },
      { label: "40g (double)", grams: 40 },
    ],
  },
  {
    name: "Hummus",
    category: "other",
    per100g: { protein: 6.7, fat: 15, carbs: 20, calories: 233.3, fiber: 6.7, sugar: 0, sodium: 433.3 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "2 tbsp (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Peanut butter, smooth",
    category: "other",
    per100g: { protein: 24.1, fat: 50.3, carbs: 21.6, calories: 587.5, fiber: 5, sugar: 10.6, sodium: 475 },
    servings: [
      { label: "16g (half serving)", grams: 16 },
      { label: "2 tbsp (32g)", grams: 32, isDefault: true },
      { label: "48g (1½ servings)", grams: 48 },
      { label: "64g (double)", grams: 64 },
    ],
  },
  {
    name: "Almond butter",
    category: "other",
    per100g: { protein: 20.9, fat: 55.9, carbs: 18.8, calories: 612.5, fiber: 10.3, sugar: 4.7, sodium: 6.3 },
    servings: [
      { label: "16g (half serving)", grams: 16 },
      { label: "2 tbsp (32g)", grams: 32, isDefault: true },
      { label: "48g (1½ servings)", grams: 48 },
      { label: "64g (double)", grams: 64 },
    ],
  },
  {
    name: "Tahini (sesame paste)",
    category: "other",
    per100g: { protein: 17, fat: 53.3, carbs: 21.3, calories: 593.3, fiber: 9.3, sugar: 0.7, sodium: 116.7 },
    servings: [
      { label: "15g (half serving)", grams: 15 },
      { label: "2 tbsp (30g)", grams: 30, isDefault: true },
      { label: "45g (1½ servings)", grams: 45 },
      { label: "60g (double)", grams: 60 },
    ],
  },
  {
    name: "Coconut milk, canned",
    category: "other",
    per100g: { protein: 1.7, fat: 18.3, carbs: 3.3, calories: 183.3, fiber: 0, sugar: 1.7, sodium: 16.7 },
    servings: [
      { label: "30g (half serving)", grams: 30 },
      { label: "1/4 cup (60g)", grams: 60, isDefault: true },
      { label: "90g (1½ servings)", grams: 90 },
      { label: "120g (double)", grams: 120 },
    ],
  },
  {
    name: "Almond milk, unsweetened",
    category: "other",
    per100g: { protein: 0.4, fat: 1, carbs: 1.4, calories: 16.3, fiber: 0.2, sugar: 0, sodium: 77.5 },
    servings: [
      { label: "120g (half serving)", grams: 120 },
      { label: "1 cup (240g)", grams: 240, isDefault: true },
      { label: "360g (1½ servings)", grams: 360 },
      { label: "480g (double)", grams: 480 },
    ],
  },
  {
    name: "Soy milk, unsweetened",
    category: "other",
    per100g: { protein: 2.9, fat: 1.6, carbs: 1.6, calories: 32.9, fiber: 0.4, sugar: 0.4, sodium: 37 },
    servings: [
      { label: "122g (half serving)", grams: 122 },
      { label: "1 cup (243g)", grams: 243, isDefault: true },
      { label: "365g (1½ servings)", grams: 365 },
      { label: "486g (double)", grams: 486 },
    ],
  },
  {
    name: "Oat milk, unsweetened",
    category: "other",
    per100g: { protein: 1.3, fat: 0.6, carbs: 6.7, calories: 33.3, fiber: 0.8, sugar: 2.9, sodium: 41.7 },
    servings: [
      { label: "120g (half serving)", grams: 120 },
      { label: "1 cup (240g)", grams: 240, isDefault: true },
      { label: "360g (1½ servings)", grams: 360 },
      { label: "480g (double)", grams: 480 },
    ],
  },
  {
    name: "Dark chocolate, 70-85%",
    category: "other",
    per100g: { protein: 7.9, fat: 43.2, carbs: 46.4, calories: 607.1, fiber: 11.1, sugar: 24.3, sodium: 21.4 },
    servings: [
      { label: "14g (half serving)", grams: 14 },
      { label: "1 oz (28g)", grams: 28, isDefault: true },
      { label: "42g (1½ servings)", grams: 42 },
      { label: "56g (double)", grams: 56 },
    ],
  },
  {
    name: "Cocoa powder, unsweetened",
    category: "other",
    per100g: { protein: 20, fat: 14, carbs: 60, calories: 240, fiber: 36, sugar: 2, sodium: 20 },
    servings: [
      { label: "3g (half serving)", grams: 3 },
      { label: "1 tbsp (5g)", grams: 5, isDefault: true },
      { label: "8g (1½ servings)", grams: 8 },
      { label: "10g (double)", grams: 10 },
    ],
  },
  {
    name: "Tomato sauce, plain",
    category: "other",
    per100g: { protein: 1.3, fat: 0.2, carbs: 5.4, calories: 23.6, fiber: 1.4, sugar: 3.6, sodium: 261 },
    servings: [
      { label: "62g (half serving)", grams: 62 },
      { label: "1/2 cup (123g)", grams: 123, isDefault: true },
      { label: "185g (1½ servings)", grams: 185 },
      { label: "246g (double)", grams: 246 },
    ],
  },
  {
    name: "Salsa",
    category: "other",
    per100g: { protein: 1.3, fat: 0.3, carbs: 6.3, calories: 28.1, fiber: 1.6, sugar: 3.8, sodium: 600 },
    servings: [
      { label: "16g (half serving)", grams: 16 },
      { label: "2 tbsp (32g)", grams: 32, isDefault: true },
      { label: "48g (1½ servings)", grams: 48 },
      { label: "64g (double)", grams: 64 },
    ],
  },
  {
    name: "Olives, black",
    category: "other",
    per100g: { protein: 1.2, fat: 13.5, carbs: 8.2, calories: 147.1, fiber: 4.1, sugar: 0, sodium: 1129.4 },
    servings: [
      { label: "9g (half serving)", grams: 9 },
      { label: "5 olives (17g)", grams: 17, isDefault: true },
      { label: "26g (1½ servings)", grams: 26 },
      { label: "34g (double)", grams: 34 },
    ],
  },
  {
    name: "Olives, green",
    category: "other",
    per100g: { protein: 1, fat: 15, carbs: 4, calories: 145, fiber: 3.5, sugar: 0.5, sodium: 2665 },
    servings: [
      { label: "10g (half serving)", grams: 10 },
      { label: "5 olives (20g)", grams: 20, isDefault: true },
      { label: "30g (1½ servings)", grams: 30 },
      { label: "40g (double)", grams: 40 },
    ],
  },
  {
    name: "Pickles, dill",
    category: "other",
    per100g: { protein: 0.6, fat: 0.3, carbs: 3.1, calories: 13.8, fiber: 1.2, sugar: 1.5, sodium: 1281.5 },
    servings: [
      { label: "33g (half serving)", grams: 33 },
      { label: "1 medium (65g)", grams: 65, isDefault: true },
      { label: "98g (1½ servings)", grams: 98 },
      { label: "130g (double)", grams: 130 },
    ],
  },
  {
    name: "Sauerkraut",
    category: "other",
    per100g: { protein: 1, fat: 0.1, carbs: 4.2, calories: 19.7, fiber: 3, sugar: 1.8, sodium: 660.6 },
    servings: [
      { label: "36g (half serving)", grams: 36 },
      { label: "1/2 cup (71g)", grams: 71, isDefault: true },
      { label: "107g (1½ servings)", grams: 107 },
      { label: "142g (double)", grams: 142 },
    ],
  },
  {
    name: "Kimchi",
    category: "other",
    per100g: { protein: 1.5, fat: 0.5, carbs: 2.1, calories: 14.7, fiber: 1.6, sugar: 1.1, sodium: 664 },
    servings: [
      { label: "38g (half serving)", grams: 38 },
      { label: "1/2 cup (75g)", grams: 75, isDefault: true },
      { label: "113g (1½ servings)", grams: 113 },
      { label: "150g (double)", grams: 150 },
    ],
  },
  {
    name: "Apple cider vinegar",
    category: "other",
    per100g: { protein: 0, fat: 0, carbs: 0.7, calories: 20, fiber: 0, sugar: 0.7, sodium: 6.7 },
    servings: [
      { label: "8g (half serving)", grams: 8 },
      { label: "1 tbsp (15g)", grams: 15, isDefault: true },
      { label: "23g (1½ servings)", grams: 23 },
      { label: "30g (double)", grams: 30 },
    ],
  },
  {
    name: "Soy sauce",
    category: "other",
    per100g: { protein: 8.1, fat: 0.6, carbs: 5, calories: 50, fiber: 0.6, sugar: 0.6, sodium: 5493.8 },
    servings: [
      { label: "8g (half serving)", grams: 8 },
      { label: "1 tbsp (16g)", grams: 16, isDefault: true },
      { label: "24g (1½ servings)", grams: 24 },
      { label: "32g (double)", grams: 32 },
    ],
  },
  {
    name: "Nutritional yeast",
    category: "other",
    per100g: { protein: 50, fat: 3.1, carbs: 31.3, calories: 375, fiber: 25, sugar: 0, sodium: 156.3 },
    servings: [
      { label: "8g (half serving)", grams: 8 },
      { label: "2 tbsp (16g)", grams: 16, isDefault: true },
      { label: "24g (1½ servings)", grams: 24 },
      { label: "32g (double)", grams: 32 },
    ],
  },
  {
    name: "Cherry tomatoes",
    category: "vegetables",
    per100g: { protein: 0.9, fat: 0.2, carbs: 3.9, calories: 18, fiber: 1.2, sugar: 2.6, sodium: 5 },
    servings: [
      { label: "1 cherry (17g)", grams: 17 },
      { label: "½ cup (74g)", grams: 74 },
      { label: "1 cup (149g)", grams: 149, isDefault: true },
      { label: "2 cups (298g)", grams: 298 },
    ],
  },
  {
    name: "Sugar snap peas",
    category: "vegetables",
    per100g: { protein: 2.8, fat: 0.1, carbs: 7.6, calories: 42, fiber: 2.6, sugar: 3.9, sodium: 3 },
    servings: [
      { label: "35g (¼ cup)", grams: 35 },
      { label: "1 cup (98g)", grams: 98, isDefault: true },
      { label: "196g (double)", grams: 196 },
    ],
  },
  {
    name: "Mixed green salad (no dressing)",
    category: "vegetables",
    per100g: { protein: 1.5, fat: 0.3, carbs: 2.5, calories: 15, fiber: 1.8, sugar: 0.8, sodium: 20 },
    servings: [
      { label: "1 cup (57g)", grams: 57 },
      { label: "2 cups / side salad (114g)", grams: 114, isDefault: true },
      { label: "large bowl (200g)", grams: 200 },
    ],
  },
  {
    name: "Hummus",
    category: "other",
    per100g: { protein: 7.9, fat: 9.6, carbs: 14.3, calories: 177, fiber: 6, sugar: 0.3, sodium: 379 },
    servings: [
      { label: "1 tbsp (15g)", grams: 15 },
      { label: "2 tbsp (30g)", grams: 30, isDefault: true },
      { label: "¼ cup (60g)", grams: 60 },
      { label: "½ cup (120g)", grams: 120 },
    ],
  },
  {
    name: "Cucumber slices",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.1, carbs: 3.6, calories: 15, fiber: 0.5, sugar: 1.7, sodium: 2 },
    servings: [
      { label: "½ cup sliced (52g)", grams: 52 },
      { label: "1 cup sliced (104g)", grams: 104, isDefault: true },
      { label: "1 whole (300g)", grams: 300 },
    ],
  },
  {
    name: "Radishes",
    category: "vegetables",
    per100g: { protein: 0.7, fat: 0.1, carbs: 3.4, calories: 16, fiber: 1.6, sugar: 1.9, sodium: 39 },
    servings: [
      { label: "1 medium (4g)", grams: 4 },
      { label: "½ cup sliced (58g)", grams: 58, isDefault: true },
      { label: "1 cup sliced (116g)", grams: 116 },
    ],
  },
  {
    name: "Green onions (scallions)",
    category: "vegetables",
    per100g: { protein: 1.8, fat: 0.2, carbs: 7.3, calories: 32, fiber: 2.6, sugar: 2.3, sodium: 16 },
    servings: [
      { label: "1 stalk (15g)", grams: 15 },
      { label: "¼ cup chopped (25g)", grams: 25, isDefault: true },
      { label: "½ cup chopped (50g)", grams: 50 },
    ],
  },
  {
    name: "Cabbage, raw",
    category: "vegetables",
    per100g: { protein: 1.3, fat: 0.1, carbs: 5.8, calories: 25, fiber: 2.5, sugar: 3.2, sodium: 18 },
    servings: [
      { label: "½ cup shredded (45g)", grams: 45 },
      { label: "1 cup shredded (89g)", grams: 89, isDefault: true },
      { label: "2 cups shredded (178g)", grams: 178 },
    ],
  },
  {
    name: "Pumpkin seeds (pepitas)",
    category: "nuts",
    per100g: { protein: 30.2, fat: 49.1, carbs: 10.7, calories: 574, fiber: 6, sugar: 1.4, sodium: 7 },
    servings: [
      { label: "1 tbsp (9g)", grams: 9 },
      { label: "2 tbsp (18g)", grams: 18, isDefault: true },
      { label: "¼ cup (35g)", grams: 35 },
    ],
  },
  {
    name: "Sunflower seeds",
    category: "nuts",
    per100g: { protein: 20.8, fat: 51.5, carbs: 20, calories: 584, fiber: 8.6, sugar: 2.6, sodium: 3 },
    servings: [
      { label: "1 tbsp (9g)", grams: 9 },
      { label: "2 tbsp (17g)", grams: 17, isDefault: true },
      { label: "¼ cup (35g)", grams: 35 },
    ],
  },
  {
    name: "Hemp seeds",
    category: "nuts",
    per100g: { protein: 31.6, fat: 48.7, carbs: 8.7, calories: 553, fiber: 4, sugar: 1.5, sodium: 5 },
    servings: [
      { label: "1 tbsp (10g)", grams: 10 },
      { label: "3 tbsp (30g)", grams: 30, isDefault: true },
      { label: "¼ cup (40g)", grams: 40 },
    ],
  },
  {
    name: "Lentils, cooked",
    category: "protein",
    per100g: { protein: 9, fat: 0.4, carbs: 20, calories: 116, fiber: 7.9, sugar: 1.8, sodium: 2 },
    servings: [
      { label: "½ cup (99g)", grams: 99 },
      { label: "1 cup (198g)", grams: 198, isDefault: true },
      { label: "1½ cups (297g)", grams: 297 },
    ],
  },
  {
    name: "Chickpeas, cooked",
    category: "protein",
    per100g: { protein: 8.9, fat: 2.6, carbs: 27.4, calories: 164, fiber: 7.6, sugar: 4.8, sodium: 7 },
    servings: [
      { label: "½ cup (82g)", grams: 82 },
      { label: "1 cup (164g)", grams: 164, isDefault: true },
      { label: "1½ cups (246g)", grams: 246 },
    ],
  },
  {
    name: "Black beans, cooked",
    category: "protein",
    per100g: { protein: 8.9, fat: 0.5, carbs: 23.7, calories: 132, fiber: 8.7, sugar: 0.3, sodium: 1 },
    servings: [
      { label: "½ cup (86g)", grams: 86 },
      { label: "1 cup (172g)", grams: 172, isDefault: true },
      { label: "1½ cups (258g)", grams: 258 },
    ],
  },
];

/** Convert a USDA food entry to the FoodItem shape used in IndexedDB. */
export function usdaToFoodItem(food: UsdaFood): Omit<import('./db').FoodItem, 'id'> {
  const defaultServing = food.servings.find(s => s.isDefault) ?? food.servings[0];
  const per = food.per100g;
  const g = defaultServing.grams;
  const scale = g / 100;

  return {
    name: food.name,
    servingLabel: defaultServing.label,
    measurementOptions: food.servings.map(s => ({
      label: s.label,
      multiplier: s.grams / g,
      grams: s.grams,
    })),
    per100g: {
      protein: per.protein,
      fat: per.fat,
      carbs: per.carbs,
      calories: per.calories,
      fiber: per.fiber,
      sodium: per.sodium,
      sugar: per.sugar,
    },
    protein: Math.round(per.protein * scale * 10) / 10,
    fat: Math.round(per.fat * scale * 10) / 10,
    carbs: Math.round(per.carbs * scale * 10) / 10,
    calories: Math.round(per.calories * scale),
    builtIn: true,
    source: 'usda' as const,
  };
}
